application:
  port: 3000
  host: 0.0.0.0
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newswave"
  require_ssl: false
redis:
  host: "localhost"
  port: 6379
smtp:
  host: localhost
  username: local
  key: local
  from_email: local@newswave.local